services:
  # üóÑÔ∏è SQL Server - DEVELOP
  exp-sqlserver-develop:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: exp-sqlserver-develop-db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin123!"
      MSSQL_PID: "Developer"
    ports:
      - "1438:1433"
    volumes:
      - sqldata_develop:/var/opt/mssql
    networks:
      - network_experiencesig
    
   

  # üóÑÔ∏è SQL Server - QA
  exp-sqlserver-qa:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: exp-sqlserver-qa-db
    
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin123!"
      MSSQL_PID: "Developer"
    ports:
      - "1436:1433"
    volumes:
      - sqldata_qa:/var/opt/mssql
    networks:
      - network_experiencesig
   
    

  # üóÑÔ∏è SQL Server - STAGING
  exp-sqlserver-staging:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: exp-sqlserver-staging-db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin123!"
      MSSQL_PID: "Developer"
    ports:
      - "1437:1433"
    volumes:
      - sqldata_staging:/var/opt/mssql
    networks:
      - network_experiencesig
  
 

   # üóÑÔ∏è SQL Server - PROD
  exp-sqlserver-prod:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: exp-sqlserver-prod-db
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Admin123!"
      MSSQL_PID: "Developer"
    ports:
      - "1435:1433"
    volumes:
      - sqldata_prod:/var/opt/mssql
    networks:
      - network_experiencesig
  
    

volumes:
  sqldata_develop:
  sqldata_qa:
  sqldata_staging:
  sqldata_prod:

networks:
  network_experiencesig:
    name: network_experiencesig
    driver: bridge
    external: false

