version: "3.9"

services:
  # üåê API principal - DEVELOP
  exp-api-develop:
    container_name: exp-api-develop
    build:
      context: ../..        # ra√≠z del repositorio
      dockerfile: API/Dockerfile
    restart: always
    env_file:
      - .env.dev
    ports:
      - "5100:8080"
    networks:
      - network_experiencesig
    labels:
      - com.exp.environment=develop

networks:
  network_experiencesig:
    external: true
